# &desc: "Paths excluded from dotfiles-backup snapshots -- secrets (secrets.fish, .envrc), build caches (__pycache__, target dirs), and machine-specific state."

{ ... }:

# The dotfiles-backup module's excludeFiles/redactValues -- no sensible
# generic default (this machine's specific sensitive paths/values), same
# reasoning as config/config.nix, just split into its own file since
# these two lists are bulkier than a flat scalar. See
# modules/backup/dotfiles/default.nix for what each option actually does.
{
  config.vars.backup.dotfilesBackup = {
    excludeFiles = [
      "Shells/Fish/secrets.fish"
      ".envrc"

      "**/__pycache__"
      "*.pyc"
      "*.pyo"
      ".mypy_cache"
      ".pytest_cache"
      ".ruff_cache"
      ".venv"
      "venv"
      ".direnv"
      ".DS_Store"

      # Rust build output for the standalone projects under Scripts/
      # (Casket, CRun, ...) -- large, machine-specific, and reproducible
      # from Cargo.lock + flake.lock, so it has no business in the
      # published snapshot.
      "**/target"

      # Casket's test fixtures/scratch data (Scripts/Casket/.test) --
      # 7.9GB, machine-local, regenerated by its own test suite, never
      # belonged in the snapshot. Found 2026-08-21: missing from this
      # list entirely was the largest single contributor to repo-cache
      # ballooning to 14GB and a dotfiles-backup push dying mid-transfer
      # (send-pack: unexpected disconnect after ~999s).
      "**/.test"
    ];
  };
}
