# --- HYPRLAND MAIN CONFIG ---

# 1.    Core Variables & Environment
source = ~/.config/hypr/Config/Core/env.conf                    # 1.1  Environment Variables

# 2.    Hardware / Input
source = ~/.config/hypr/Config/Core/monitors.conf               # 2.1  Monitor Configuration
source = ~/.config/hypr/Config/Core/input.conf                  # 2.2  Input

# 3.    Visuals & UI
source = ~/.config/hypr/Config/UI/theme.conf                    # 3.1  Look & Feel
source = ~/.config/hypr/Config/UI/workspaces.conf               # 3.2  Workspaces

# 4.    Window Management & Rules
source = ~/.config/hypr/Config/Rules/layout.conf                # 4.1  Workspaces
source = ~/.config/hypr/Config/Rules/rules.conf                 # 4.2  Permissions

# 5.    Apps & Autostart
source = ~/.config/hypr/Config/Apps/defaults.conf               # 5.1  Default Programms
source = ~/.config/hypr/Config/Apps/autostart.conf              # 5.2  Autostart

# 6.    Keybindings
source = ~/.config/hypr/Config/Binds/apps.conf                  # 6.1  App launchers
source = ~/.config/hypr/Config/Binds/binds.conf                 # 6.2  General KBM Shortcuts
source = ~/.config/hypr/Config/Binds/laptop.conf                # 6.3  Laptop MEDIA shortcuts
# source = ~/.config/hypr/Config/Binds/windows.conf               # 6.4  Window management
source = ~/.config/hypr/Config/Binds/media.conf                 # 6.5  Media control 
source = ~/.config/hypr/Config/Binds/system.conf                # 6.5  System controls 
source = ~/.config/hypr/Config/Binds/plugins.conf               # 6.6  Plugin binds 

# 7.    Plugins
source = ~/.config/hypr/Config/Plugins/easymotion.conf          # 7.1  Easy motion plugin
source = ~/.config/hypr/Config/Plugins/hyprexpo.conf            # 7.2  Hyprexpo settings
source = ~/.config/hypr/Config/Plugins/borders-plus-plus.conf   # 7.3  Enhanced borders
source = ~/.config/hypr/Config/Plugins/hyprwinwrap.conf         # 7.4  Video wallpapers
source = ~/.config/hypr/Config/Plugins/dynamic-cursors.conf     # 7.5  Cursor animations
source = ~/.config/hypr/Config/Plugins/hyprscroll.conf          # 7.6  Hyprscroll config

# 8.    Reactive [Files that are modified by script]
source = ~/.config/hypr/Config/Reactive/windowMode.conf         # 8.1  Window mode manipulation

# 9.    External
source = ~/Projects/FloatingWM/sourceMe.conf