# Installed Apps
bind = $mainMod, V, exec, vesktop
bind = $mainMod, S, exec, steam
bind = $mainMod, K, exec, keepassxc
bind = $mainMod, Z, exec, zapzap

# Deprecated yay installation
# bind = $mainMod, M, exec, modrinth-app

# Variable based
bind = $mainMod, Y, exec, $browser
bind = $mainMod, C, exec, $editor
bind = $mainMod, T, exec, $terminal
bind = $mainMod, E, exec, $fileManager

# Terminal apps | KITTY
# bind = $mainMod ALT, C, exec, kitty --hold -o confirm_os_window_close=0 /home/herauxvalle/Scripts/Shell/Bash/claudetrust.sh
bind = $mainMod ALT, E, exec, kitty --hold -o confirm_os_window_close=0 yazi
bind = $mainMod ALT, T, exec, kitty --hold -o confirm_os_window_close=0 fresh
bind = $mainMod ALT, V, exec, kitty --hold -o confirm_os_window_close=0 pulsemixer
bind = $mainMod, M, exec, kitty -o close_on_child_death=yes -e bash /home/herauxvalle/Scripts/Shell/Vaults/modrinth.sh

# Usefull gadgets
bind = $mainMod ALT, SPACE, exec, bash -c "kitty --class menu-float -e fish -c launcher || $menu -show drun"
bind = $mainMod, P, exec, hyprpicker -a -f hex && notify-send "Color copied!"
bind = $mainMod ALT, N, exec, nm-connection-editor

