# Reboot & Shutdown
bind = $mainMod ALT, R, exec, systemctl reboot
bind = $mainMod ALT, S, exec, systemctl poweroff
bind = $mainMod ALT, X, exec, systemctl suspend

# Hyprland
bind = $mainMod SHIFT, Q, exec, kill -9 $(hyprctl activewindow -j | jq '.pid')
bind = $mainMod, Q, exec, hyprctl dispatch closewindow active
bind = $mainMod, L, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# Refresh everything
bind = $mainMod, R, exec, ~/Scripts/Shell/Bash/qsr.sh