# --- Custom Autostart ---
exec-once = ~/Scripts/Shell/Bash/wallpaper.sh
exec-once = qs
exec-once = pypr
exec-once = mpd
exec-once = swaync
exec-once = ~/Projects/MyBar/main.sh --launch

# --- Essential Session Glue ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QUICK_CONTROLS_STYLE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QUICK_CONTROLS_STYLE

# --- Theme Handlers ---
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# --- Custom Dolphin Fix ---
# Fix "open with bug"
exec-once = bash -c 'prefix=$(ls /etc/xdg/menus/ 2>/dev/null | grep -m1 "applications.menu$" | sed "s/applications.menu$//"); XDG_MENU_PREFIX=${prefix:-} kbuildsycoca6 --noincremental'
# exec-once = XDG_MENU_PREFIX=arch- kbuildsycoca6 --noincremental

# --- Default App Handlers ---
exec-once = xdg-settings set default-web-browser $browser.desktop
exec-once = xdg-mime default $editor.desktop text/plain
exec-once = xdg-mime default $fileManager.desktop inode/directory

# --- Hyprpm plugins ---
exec-once = hyprpm reload

# --- Set all monitors to workspace 1 ---
exec-once = ~/Scripts/Shell/Bash/defaultWS.sh
exec-once = ~/Scripts/Shell/Bash/defaultApps.sh
