-- canvas plugin: ComfyUI-style infinite pan/zoom canvas
-- (see Hyprland/plugins/canvas/DESIGN.md for the full design)
--
-- Toggle is the only discrete keybind the plugin needs. Zoom
-- (Meta+Shift+Scroll) and pan (Meta+Shift+Right-Drag) are handled entirely
-- inside the plugin via raw mouse hooks, not exposed as Hyprland dispatchers
-- or binds -- see DESIGN.md's "Rejected alternatives" for why. Binding them
-- here too (as an earlier version of this file did, for zoom/reset/arrow-pan)
-- would have called hl.plugin.canvas.zoom/.reset/.pan, which don't exist:
-- the plugin only ever registers a "toggle" entry point.
hl.bind(mainMod .. " + SHIFT + C", function() hl.plugin.canvas.toggle() end)
