#ifndef SD_INIT_SECCOMP_H
#define SD_INIT_SECCOMP_H

#include <linux/seccomp.h>
#include <linux/filter.h>
#include <linux/bpf_common.h>
#include <stddef.h>

/* Strict allowlist seccomp filter
 * Allows: 140 syscalls
 * Explicitly blocks: 14 dangerous syscalls
 * Default: SCMP_ACT_KILL_PROCESS
 * clone() filtered: only pthread-safe flags allowed
 */
static struct sock_filter sd_seccomp_filter[] = {
    { .code = BPF_LD | BPF_W | BPF_ABS, .jt = 0, .jf = 0, .k = offsetof(struct seccomp_data, nr) },
    /* Allow read (0) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 0 },
    /* Allow write (1) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 1 },
    /* Allow open (2) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 2 },
    /* Allow close (3) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 3 },
    /* Allow stat (4) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 4 },
    /* Allow fstat (5) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 5 },
    /* Allow lstat (6) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 6 },
    /* Allow poll (7) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 7 },
    /* Allow lseek (8) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 8 },
    /* Allow mmap (9) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 9 },
    /* Allow mprotect (10) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 10 },
    /* Allow munmap (11) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 11 },
    /* Allow brk (12) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 12 },
    /* Allow rt_sigaction (13) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 13 },
    /* Allow rt_sigprocmask (14) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 14 },
    /* Allow access (21) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 21 },
    /* Allow pause (34) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 34 },
    /* Allow nanosleep (35) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 35 },
    /* Allow getitimer (36) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 36 },
    /* Allow alarm (37) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 37 },
    /* Allow setitimer (38) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 38 },
    /* Allow getpid (39) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 39 },
    /* Allow socket (41) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 41 },
    /* Allow connect (42) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 42 },
    /* Allow accept (43) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 43 },
    /* Allow sendto (44) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 44 },
    /* Allow recvfrom (45) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 45 },
    /* Allow sendmsg (46) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 46 },
    /* Allow recvmsg (47) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 47 },
    /* Allow shutdown (48) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 48 },
    /* Kill ptrace (101) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 101 },
    /* Kill pivot_root (155) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 155 },
    /* Kill mount (165) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 165 },
    /* Kill umount2 (166) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 166 },
    /* Kill init_module (175) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 175 },
    /* Kill delete_module (176) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 176 },
    /* Kill kexec_load (246) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 246 },
    /* Kill unshare (272) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 272 },
    /* Kill setns (308) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 308 },
    /* Kill process_vm_readv (310) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 310 },
    /* Kill process_vm_writev (311) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 311 },
    /* Kill finit_module (313) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 313 },
    /* Kill kexec_file_load (320) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 320 },
    /* Kill bpf (321) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 201, .jf = 0, .k = 321 },
    /* Allow bind (49) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 49 },
    /* Allow listen (50) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 50 },
    /* Allow getsockname (51) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 51 },
    /* Allow getpeername (52) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 52 },
    /* Allow socketpair (53) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 53 },
    /* Allow setsockopt (54) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 54 },
    /* Allow getsockopt (55) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 55 },
    /* Allow clone (56) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 56 },
    /* Allow fork (57) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 57 },
    /* Allow vfork (58) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 58 },
    /* Allow execve (59) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 59 },
    /* Allow exit (60) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 60 },
    /* Allow kill (62) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 62 },
    /* Allow uname (63) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 63 },
    /* Allow fcntl (72) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 72 },
    /* Allow flock (73) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 73 },
    /* Allow fsync (74) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 74 },
    /* Allow fdatasync (75) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 75 },
    /* Allow truncate (76) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 76 },
    /* Allow ftruncate (77) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 77 },
    /* Allow getdents (78) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 78 },
    /* Allow getcwd (79) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 79 },
    /* Allow chdir (80) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 80 },
    /* Allow fchdir (81) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 81 },
    /* Allow rename (82) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 82 },
    /* Allow mkdir (83) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 83 },
    /* Allow rmdir (84) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 84 },
    /* Allow creat (85) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 85 },
    /* Allow link (86) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 86 },
    /* Allow unlink (87) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 87 },
    /* Allow symlink (88) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 88 },
    /* Allow readlink (89) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 89 },
    /* Allow chmod (90) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 90 },
    /* Allow fchmod (91) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 91 },
    /* Allow chown (92) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 92 },
    /* Allow fchown (93) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 93 },
    /* Allow lchown (94) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 94 },
    /* Allow gettimeofday (96) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 96 },
    /* Allow umask (96) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 96 },
    /* Allow getrlimit (97) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 97 },
    /* Allow getrusage (98) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 98 },
    /* Allow sysinfo (99) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 99 },
    /* Allow getgid (104) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 104 },
    /* Allow getuid (104) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 104 },
    /* Allow setuid (105) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 105 },
    /* Allow setgid (106) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 106 },
    /* Allow geteuid (107) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 107 },
    /* Allow getegid (108) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 108 },
    /* Allow setpgid (109) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 109 },
    /* Allow getppid (110) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 110 },
    /* Allow getpgrp (111) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 111 },
    /* Allow setsid (112) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 112 },
    /* Allow setreuid (113) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 113 },
    /* Allow setregid (114) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 114 },
    /* Allow getgroups (115) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 115 },
    /* Allow setgroups (116) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 116 },
    /* Allow setresuid (117) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 117 },
    /* Allow getresuid (118) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 118 },
    /* Allow setresgid (119) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 119 },
    /* Allow getresgid (120) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 120 },
    /* Allow getpgid (121) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 121 },
    /* Allow setfsuid (122) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 122 },
    /* Allow setfsgid (123) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 123 },
    /* Allow capget (125) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 125 },
    /* Allow capset (126) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 126 },
    /* Allow rt_sigpending (127) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 127 },
    /* Allow rt_sigtimedwait (128) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 128 },
    /* Allow sigaltstack (131) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 131 },
    /* Allow personality (135) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 135 },
    /* Allow arch_prctl (158) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 158 },
    /* Allow getdents64 (217) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 217 },
    /* Allow set_tid_address (218) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 218 },
    /* Allow semtimedop (220) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 220 },
    /* Allow clock_settime (227) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 227 },
    /* Allow clock_gettime (228) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 228 },
    /* Allow clock_nanosleep (230) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 230 },
    /* Allow exit_group (231) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 231 },
    /* Allow epoll_wait (232) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 232 },
    /* Allow epoll_ctl (233) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 233 },
    /* Allow tgkill (234) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 234 },
    /* Allow mq_open (240) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 240 },
    /* Allow mq_notify (244) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 244 },
    /* Allow mq_getsetattr (245) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 245 },
    /* Allow openat (257) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 257 },
    /* Allow mkdirat (258) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 258 },
    /* Allow fchownat (260) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 260 },
    /* Allow unlinkat (263) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 263 },
    /* Allow renameat (264) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 264 },
    /* Allow linkat (265) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 265 },
    /* Allow symlinkat (266) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 266 },
    /* Allow readlinkat (267) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 267 },
    /* Allow fchmodat (268) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 268 },
    /* Allow faccessat (269) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 269 },
    /* Allow pselect6 (270) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 270 },
    /* Allow ppoll (271) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 271 },
    /* Allow set_robust_list (273) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 273 },
    /* Allow epoll_pwait (281) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 281 },
    /* Allow accept4 (288) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 288 },
    /* Allow epoll_create1 (291) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 291 },
    /* Allow dup3 (292) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 292 },
    /* Allow pipe2 (293) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 293 },
    /* Allow preadv (295) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 295 },
    /* Allow pwritev (296) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 296 },
    /* Allow prlimit64 (302) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 302 },
    /* Allow clock_adjtime (305) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 305 },
    /* Allow renameat2 (316) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 316 },
    /* Allow getrandom (318) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 318 },
    /* Allow execveat (322) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 322 },
    /* Allow statx (332) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 332 },
    /* Allow epoll_pwait2 (441) */ { .code = BPF_JMP | BPF_JEQ | BPF_K, .jt = 200, .jf = 0, .k = 441 },
    /* Default deny */ { .code = BPF_RET | BPF_K, .jt = 0, .jf = 0, .k = SECCOMP_RET_KILL_PROCESS },
    /* Allow */ { .code = BPF_RET | BPF_K, .jt = 0, .jf = 0, .k = SECCOMP_RET_ALLOW },
    /* Kill */ { .code = BPF_RET | BPF_K, .jt = 0, .jf = 0, .k = SECCOMP_RET_KILL_PROCESS },

};

static struct sock_fprog sd_seccomp_prog = {
    .len = sizeof(sd_seccomp_filter) / sizeof(sd_seccomp_filter[0]),
    .filter = sd_seccomp_filter,
};

#endif
