// build.rs
//
// Auto-discovers language backends in src/languages/ so adding a new language
// is just "drop a directory in there" — no manual mod declarations or registry edits.
//
// Each subdirectory of src/languages/ is assumed to be a language module with:
//   config.rs — pub fn config() -> CompilerConfig          (required)
//   deps.rs   — pub fn deps() -> DepSpec                   (optional)
//   test.rs   — pub fn run_test() -> Result<(), String>    (optional)
//
// We generate a small Rust file into OUT_DIR declaring each present file as a
// submodule and collecting their exports into all_languages() / all_dep_specs()
// / all_test_runners(), which language.rs includes verbatim.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let languages_dir = Path::new("src/languages");
    println!("cargo:rerun-if-changed={}", languages_dir.display());

    let mut modules = Vec::new();
    for entry in fs::read_dir(languages_dir).expect("failed to read src/languages") {
        let entry = entry.expect("failed to read dir entry");
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let name = path.file_name().unwrap().to_str().unwrap().to_string();

        let has_config = path.join("config.rs").is_file();
        if !has_config {
            continue; // not a language module
        }
        let has_deps = path.join("deps.rs").is_file();
        let has_test = path.join("test.rs").is_file();

        println!("cargo:rerun-if-changed={}", path.display());
        modules.push((name, has_deps, has_test));
    }
    modules.sort_by(|a, b| a.0.cmp(&b.0));

    // On Windows CARGO_MANIFEST_DIR uses backslashes (e.g. `D:\a\CRun\CRun`),
    // which would need escaping inside the generated `#[path = "..."]` string
    // literals. Forward slashes work fine in Rust path attributes on every
    // platform, so normalize once here instead of escaping.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap().replace('\\', "/");

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n\n");

    for (m, has_deps, has_test) in &modules {
        let base = format!("{manifest_dir}/src/languages/{m}", manifest_dir = manifest_dir, m = m);
        out.push_str(&format!("pub mod {m} {{\n", m = m));
        out.push_str(&format!("    #[path = \"{base}/config.rs\"]\n    pub mod config;\n", base = base));
        if *has_deps {
            out.push_str(&format!("    #[path = \"{base}/deps.rs\"]\n    pub mod deps;\n", base = base));
        }
        if *has_test {
            out.push_str(&format!("    #[path = \"{base}/test.rs\"]\n    pub mod test;\n", base = base));
        }
        out.push_str("}\n");
    }

    out.push_str("\npub fn all_languages() -> Vec<CompilerConfig> {\n    vec![\n");
    for (m, _, _) in &modules {
        out.push_str(&format!("        {}::config::config(),\n", m));
    }
    out.push_str("    ]\n}\n");

    out.push_str("\npub fn all_dep_specs() -> Vec<DepSpec> {\n    vec![\n");
    for (m, has_deps, _) in &modules {
        if *has_deps {
            out.push_str(&format!("        {}::deps::deps(),\n", m));
        }
    }
    out.push_str("    ]\n}\n");

    out.push_str("\n/// (display name, runner fn) for every language exposing a bundled test.\n");
    out.push_str("pub fn all_test_runners() -> Vec<(&'static str, fn() -> Result<(), String>)> {\n    vec![\n");
    for (m, _, has_test) in &modules {
        if *has_test {
            out.push_str(&format!(
                "        (\"{m}\", {m}::test::run_test as fn() -> Result<(), String>),\n",
                m = m
            ));
        }
    }
    out.push_str("    ]\n}\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("language_registry.rs");
    fs::write(&dest, out).expect("failed to write generated language registry");
}
