osc=no
border=no
keep-open=yes
save-position-on-quit=yes
hwdec=auto-safe
gpu-context=wayland
profile=gpu-hq
autocreate-playlist=filter
ytdl-raw-options=extractor-args=youtube:player_client=tv,cookies-from-browser=vivaldi
