# --- Keybinds ---

# Theming
bind = $mainMod, K, exec, kvantummanager
bind = $mainMod SHIFT, K, exec, qt6ct
bind = $mainMod ALT SHIFT, K, exec, qt5ct

# Screenshot
bind = $mainMod SHIFT, S, exec, ~/Scripts/Shell/Bash/screenshot.sh
bind = $mainMod SHIFT, P, exec, ~/Scripts/Shell/Bash/screenshot.sh --clipboard --save

# Backups
bind = $mainMod CONTROL SHIFT ALT, B, exec, ~/Scripts/Shell/Bash/timeshiftBac.sh

# SWAYNC
bind = SUPER, N, exec, swaync-client -t
bind = SUPER SHIFT, N, exec, swaync-client -d

bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod ALT, D, exec, ~/Scripts/Shell/Bash/FWM.sh



