# --- Workspace Switching ---

# Move focus with mainMod + arrow keys
bind = $mainMod CTRL SHIFT, left, movefocus, l
bind = $mainMod CTRL SHIFT, right, movefocus, r
bind = $mainMod CTRL SHIFT, up, movefocus, u
bind = $mainMod CTRL SHIFT, down, movefocus, d

# Resize windows
bind = $mainMod CTRL, left,  resizeactive, -20 0
bind = $mainMod CTRL, right, resizeactive,  20 0
bind = $mainMod CTRL, up,    resizeactive,  0 -20
bind = $mainMod CTRL, down,  resizeactive,  0  20

# Example special workspace (scratchpad)
bind = $mainMod ALT, W, togglespecialworkspace
bind = $mainMod SHIFT, W, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
# bind = $mainMod, mouse_down, workspace, e+1
# bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow, layout:!scrolling
bindm = $mainMod, mouse:273, resizewindow

# Fullscreen (real)
bind = $mainMod ALT, F, fullscreen, 0
bind = $mainMod, F, fullscreen, 1

# Cycle windows
bind = ALT, Tab, cyclenext
bind = ALT SHIFT, Tab, cyclenext, prev

# Modes
bind = $mainMod, D, togglefloating,
bind = $mainMod CTRL, D, pseudo, # dwindle
bind = $mainMod ALT, D, togglesplit, # dwindle



