[Appearance]
color_scheme_path=/home/herauxvalle/.config/qt6ct/style-colors.conf
custom_palette=true
icon_theme=breeze
standard_dialogs=kde
style=kvantum-dark

[Fonts]
fixed="Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=General
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=/nix/store/493jmw5qngr396bm73frx9wbkbip62x9-qt6ct-0.11/share/qt6ct/qss/fusion-fixes.qss, /nix/store/493jmw5qngr396bm73frx9wbkbip62x9-qt6ct-0.11/share/qt6ct/qss/scrollbar-simple.qss, /nix/store/493jmw5qngr396bm73frx9wbkbip62x9-qt6ct-0.11/share/qt6ct/qss/sliders-simple.qss, /nix/store/493jmw5qngr396bm73frx9wbkbip62x9-qt6ct-0.11/share/qt6ct/qss/tooltip-simple.qss, /nix/store/493jmw5qngr396bm73frx9wbkbip62x9-qt6ct-0.11/share/qt6ct/qss/traynotification-simple.qss, /home/herauxvalle/.config/nostripes.qss
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\x1h\0\0\x4\xdc\0\0\x6\xd5\0\0\0\0\0\0\x1h\0\0\x4\xdc\0\0\x6\xd5\0\0\0\x1\x2\0\0\0\n\0\0\0\0\0\0\0\x1h\0\0\x4\xdc\0\0\x6\xd5)

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
