// &desc: "`cas <vault> auth keyfile reset [location]` -- overwrites the active keyfile with freshly generated bytes and re-keys the LUKS slot to match (merged with the never-shipped 'regenerate' idea). No location: in place, same name/path/form. Directory: keep the name, new raw file there. File path: that becomes the new name. Irreversible -- old key material is gone the moment the new slot verifies, so new bytes are always staged and confirmed working before the old ones are touched."
use std::path::Path;

use crate::commands::settings::gate::gate_pw;
use crate::ctx::Ctx;
use crate::die;
use crate::error::Result;
use crate::header::relocate;
use crate::keyfile;
use crate::logf;
use crate::luks;
use crate::meta::Meta;
use crate::secret::{b64_encode, combined_secret, resolve_lexically};
use crate::udisks;
use crate::vault::Vault;

use super::resolve_current;

pub fn run(ctx: &Ctx, vault: &Vault, location: Option<&Path>, kf_override: Option<&Path>, pw: Option<&str>) -> Result<()> {
    if !vault.img.exists() {
        die!("vault '{}' not found", vault.name);
    }
    if vault.is_mount() {
        die!("vault is open — close it first:  cas {} close", vault.name);
    }

    let mut meta = Meta::read(&vault.img);
    let current = resolve_current(ctx, vault, &mut meta, kf_override)?;
    let pw = gate_pw(ctx, vault, "keyfileReset", pw)?;

    let old_bytes = keyfile::read_bytes(&current)?;
    let old_secret = combined_secret(&pw, &old_bytes);
    let embedded = keyfile::is_embedded(&current);

    let dest = match location {
        Some(loc) => {
            let loc = resolve_lexically(loc);
            if loc.is_dir() {
                loc.join(current.file_name().unwrap_or_default())
            } else {
                loc
            }
        }
        None => current.clone(),
    };
    let in_place = dest == current;

    let mut new_bytes = [0u8; 64];
    rand::RngCore::fill_bytes(&mut rand::thread_rng(), &mut new_bytes);
    let new_secret = combined_secret(&pw, &new_bytes);

    // Snapshot whatever's at `dest` right now so a slot_cycle failure can
    // restore it exactly, then write the new key material *before*
    // touching the LUKS slot -- same ordering settings::twofa::on() uses,
    // so a failure always rolls back forward-written bytes rather than
    // trying to reconstruct destroyed ones.
    let in_place_backup = if in_place { Some(std::fs::read(&dest)?) } else { None };
    if in_place && embedded {
        keyfile::write_embedded(&dest, &new_bytes)?;
    } else {
        std::fs::write(&dest, new_bytes)?;
        if !in_place {
            udisks::chown_to_real_user(&dest)?;
        }
    }

    logf!(ctx, "[cas] resetting keyfile for '{}' ...", vault.name);
    Meta::strip(&vault.img)?;
    // Same relocation-awareness as auth::passwd and settings::twofa's
    // cycle_secret -- if headerOffset and/or headerEncryption is on, the
    // container's front bytes aren't a directly-testable plain LUKS2
    // header, so a bare slot_cycle against the raw front fails. This
    // call site had none of that awareness at all until now — confirmed
    // live 2026-08-17 to fail identically to the twofa.rs bug for the
    // same reason.
    let cycle_result: Result<()> = if !relocate::is_native_front(&meta) {
        (|| -> Result<()> {
            let salt = crate::header::room::read_salt(&vault.img).ok_or_else(|| crate::error::CasError::new("header room not found — vault metadata is inconsistent"))?;
            let master = crate::header::derive_master_secret(&[old_secret.as_slice()], &salt);
            let staged = relocate::stage_current_header(vault, &meta, Some(&master))?;
            luks::slot_cycle_detached(ctx, staged.path(), &vault.img, &old_secret, &new_secret, None)
        })()
    } else {
        luks::slot_cycle(ctx, &vault.img, &old_secret, &new_secret, None)
    };
    if let Err(e) = cycle_result {
        meta.write(&vault.img)?;
        match in_place_backup {
            Some(old) => {
                let _ = std::fs::write(&dest, &old);
            }
            None => {
                let _ = std::fs::remove_file(&dest);
            }
        }
        return Err(e);
    }

    // Same discipline as auth::passwd and settings::twofa: the new keyfile
    // bytes just invalidated any existing header-room slot/key (both are
    // derived from the keyfile bytes), so relocate before committing the
    // new keyfile path, strictly between slot_cycle succeeding and the
    // final meta.write() -- relocate_if_enabled does its own verify-then-
    // commit-then-scrub dance under the *new* secret.
    //
    // No rollback of `dest`'s bytes on failure here, unlike the slot_cycle
    // error arm above -- slot_cycle already committed at this point, so
    // `new_secret` (which needs the new bytes) is the *only* secret that
    // still unlocks the vault. Restoring the old bytes would desync the
    // keyfile from the LUKS slot instead of protecting against anything.
    if let Err(e) = relocate::relocate_if_enabled(ctx, vault, &mut meta, &old_secret, &new_secret, None) {
        meta.write(&vault.img)?;
        return Err(e);
    }

    if !in_place {
        let _ = std::fs::remove_file(&current);
    }
    meta.keyfile = Some(dest.to_string_lossy().into_owned());
    if meta.encrypted == Some(false) {
        meta.autokey = Some(b64_encode(&new_secret));
    }
    meta.write(&vault.img)?;
    logf!(ctx, "[✓] keyfile reset — new key at {}", dest.display());
    logf!(ctx, "    the old key material is gone; anything relying on the previous bytes (backups, embedded copies) no longer works");
    Ok(())
}
