return function(_args)
    print("Keybinds (leader = Space):")
    print("")
    print("  General")
    print("    <leader>w       Save")
    print("    <leader>q       Quit")
    print("    <leader>Q       Force quit")
    print("    <leader>sv      Reload config")
    print("    Alt+:           Command mode (from any mode)")
    print("")
    print("  Splits")
    print("    <leader>sp      Split horizontal")
    print("    <leader>vsp     Split vertical")
    print("    <leader>clo     Close split")
    print("    Ctrl+h/j/k/l    Move between splits")
    print("    Ctrl+d/u        Scroll down/up (centered)")
    print("")
    print("  Explorer")
    print("    <leader>e       Toggle neo-tree")
    print("    <leader>o       Focus neo-tree")
    print("")
    print("  Telescope")
    print("    <leader>ff      Find files")
    print("    <leader>fg      Live grep")
    print("    <leader>fb      Buffers")
    print("    <leader>fr      Recent files")
    print("    <leader>fc      Theme picker")
    print("    <leader>ft      Find TODOs")
    print("")
    print("  LSP")
    print("    gd              Go to definition")
    print("    gD              Go to declaration")
    print("    gr              References")
    print("    K               Hover docs")
    print("    <leader>rn      Rename")
    print("    <leader>a       Code action")
    print("    <leader>d       Diagnostics")
    print("    [d / ]d         Prev/next diagnostic")
    print("")
    print("  Buffers")
    print("    Tab / S-Tab     Next/prev buffer")
    print("    <leader>x       Close buffer")
    print("")
    print("  Terminal")
    print("    Ctrl+t          Toggle terminal")
    print("    <leader>gg      Lazygit")
    print("    <leader>gd      Lazydocker")
    print("    Esc             Exit terminal mode")
    print("")
    print("  Run")
    print("    <leader>rr      Run current file")
    print("")
    print("  Misc")
    print("    <leader>u       Toggle undotree")
    print("    <leader>f       Format file")
    print("    gcc             Toggle comment (line)")
    print("    gc              Toggle comment (visual)")
    print("    ]t / [t         Next/prev TODO")
end
