#&desc: uosc theming - orange accent, full control set, chapter/time display
timeline_style=line
timeline_size=44
timeline_border=1
color=foreground=e1a83c,background=000000
controls_size=40
controls_margin=8
top_bar=no-border
top_bar_title=yes
controls=menu,gap,subtitles,<has_many_audio>audio,<has_many_video>video,gap,space,speed,shuffle,loop-playlist,loop-file,gap,playlist,prev,<video,audio>command:replay_10:seek%20-10?Seek%20back%2010s,play-pause,<video,audio>command:forward_10:seek%2010?Seek%20forward%2010s,next,space,gap,<video,audio>command:picture_in_picture_alt:cycle%20ontop?Always%20on%20top,command:info:script-binding%20stats/display-stats-toggle?Info,fullscreen
