#&desc: uosc theming - orange accent, full control set, chapter/time display
timeline_style=line
timeline_size=40
progress_size=2
timeline_line_width=2
timeline_border=1
destination_time=total
color=e1a83c
controls_size=40
controls_margin=8
top_bar=no-border
top_bar_title=yes
controls=menu,command:info:script-binding stats/display-stats-toggle?Info,gap,space,<has_many_audio>audio,<has_many_video>video,shuffle,prev,<video,audio>command:replay_10:seek -10?Seek back 10s,play-pause,<video,audio>command:forward_10:seek 10?Seek forward 10s,next,loop-file,space,gap,<video,audio>subtitles,playlist,<video,audio>command:picture_in_picture_alt:cycle ontop?Always on top,fullscreen
